image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

stages:
  - build
  - push

before_script:
  # Log in to the GitLab Container Registry using CI/CD environment variables
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build:
  stage: build
  script:
    # Build the Docker image using the Dockerfile in the root directory
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"