services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD:
      DB_DATABASE: kilohealth
      DB_PORT: 3306
    command: >
      sh -c "php artisan migrate && php artisan db:seed"
    volumes:
      - .:/var/www
      - /var/www/vendor/
      - /var/www/node_modules/
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: kiloblog
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kilohealth
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge