services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    environment:
      DB_HOST: host.docker.internal
      DB_USERNAME: root
      DB_PASSWORD:
      DB_DATABASE: kilohealth3
      DB_PORT: 3306
    entrypoint: |
      sh -c "
        php artisan migrate --force &&
        if [ \"$(php artisan db:seed --force --no-interaction || echo 'seeded')\" != 'seeded' ]; then
          echo 'Database already seeded. Skipping.'; 
        else 
          php artisan db:seed --force; 
        fi &&
        exec apache2-foreground
      "
    volumes:
      - .:/var/www
      - /var/www/vendor/
      - /var/www/node_modules/
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: kiloblog
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kilohealth3
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
